//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.29 at 04:00:35 pm CEST 
//


package gde.device.estner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Active_Channel"/>
 *         &lt;element ref="{}Channel1"/>
 *         &lt;element ref="{}Channel2"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "activeChannel",
    "channel1",
    "channel2"
})
@XmlRootElement(name = "Dialog-Settings")
public class DialogSettings {

    @XmlElement(name = "Active_Channel", required = true)
    protected Integer activeChannel;
    @XmlElement(name = "Channel1", required = true)
    protected ActiveSetting channel1;
    @XmlElement(name = "Channel2", required = true)
    protected ActiveSetting channel2;

    /**
     * Gets the value of the activeChannel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getActiveChannel() {
        return activeChannel;
    }

    /**
     * Sets the value of the activeChannel property.
     * 
     * @param i
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setActiveChannel(int i) {
        this.activeChannel = i;
    }

    /**
     * Gets the value of the channel1 property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveSetting }
     *     
     */
    public ActiveSetting getChannel1() {
        return channel1;
    }

    /**
     * Sets the value of the channel1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveSetting }
     *     
     */
    public void setChannel1(ActiveSetting value) {
        this.channel1 = value;
    }

    /**
     * Gets the value of the channel2 property.
     * 
     * @return
     *     possible object is
     *     {@link ActiveSetting }
     *     
     */
    public ActiveSetting getChannel2() {
        return channel2;
    }

    /**
     * Sets the value of the channel2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActiveSetting }
     *     
     */
    public void setChannel2(ActiveSetting value) {
        this.channel2 = value;
    }

}
