//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.29 at 04:00:35 pm CEST 
//


package gde.device.estner;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gde.device.estner package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CurrentMode_QNAME = new QName("", "CurrentMode");
    private final static QName _ChargeMode_QNAME = new QName("", "ChargeMode");
    private final static QName _Program_QNAME = new QName("", "Program");
    private final static QName _DisChargeCurrent_QNAME = new QName("", "DisChargeCurrent");
    private final static QName _Channel_QNAME = new QName("", "Channel");
    private final static QName _Amount_QNAME = new QName("", "Amount");
    private final static QName _SettingType_QNAME = new QName("", "SettingType");
    private final static QName _Cycle_QNAME = new QName("", "Cycle");
    private final static QName _ChargeCurrent_QNAME = new QName("", "ChargeCurrent");
    private final static QName _Channel1_QNAME = new QName("", "Channel1");
    private final static QName _Channel2_QNAME = new QName("", "Channel2");
    private final static QName _Capacity_QNAME = new QName("", "Capacity");
    private final static QName _AccuTyp_QNAME = new QName("", "AccuTyp");
    private final static QName _CellCount_QNAME = new QName("", "CellCount");
    private final static QName _ChargeStopMode_QNAME = new QName("", "ChargeStopMode");
    private final static QName _ActiveSetting_QNAME = new QName("", "Active_Setting");
    private final static QName _ActiveChannel_QNAME = new QName("", "Active_Channel");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gde.device.estner
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DialogSettings }
     * 
     */
    public DialogSettings createDialogSettings() {
        return new DialogSettings();
    }

    /**
     * Create an instance of {@link ParameterSettings }
     * 
     */
    public ParameterSettings createParameterSettings() {
        return new ParameterSettings();
    }

    /**
     * Create an instance of {@link AMSettings }
     * 
     */
    public AMSettings createAMSettings() {
        return new AMSettings();
    }

    /**
     * Create an instance of {@link Setting }
     * 
     */
    public Setting createSetting() {
        return new Setting();
    }

    /**
     * Create an instance of {@link AkkuSettings }
     * 
     */
    public AkkuSettings createAkkuSettings() {
        return new AkkuSettings();
    }

    /**
     * Create an instance of {@link ActiveSetting }
     * 
     */
    public ActiveSetting createActiveSetting() {
        return new ActiveSetting();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CurrentMode")
    public JAXBElement<BigInteger> createCurrentMode(BigInteger value) {
        return new JAXBElement<BigInteger>(_CurrentMode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargeMode")
    public JAXBElement<BigInteger> createChargeMode(BigInteger value) {
        return new JAXBElement<BigInteger>(_ChargeMode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Program")
    public JAXBElement<BigInteger> createProgram(BigInteger value) {
        return new JAXBElement<BigInteger>(_Program_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DisChargeCurrent")
    public JAXBElement<BigInteger> createDisChargeCurrent(BigInteger value) {
        return new JAXBElement<BigInteger>(_DisChargeCurrent_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Channel")
    public JAXBElement<BigInteger> createChannel(BigInteger value) {
        return new JAXBElement<BigInteger>(_Channel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Amount")
    public JAXBElement<BigInteger> createAmount(BigInteger value) {
        return new JAXBElement<BigInteger>(_Amount_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SettingType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createSettingType(String value) {
        return new JAXBElement<String>(_SettingType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cycle")
    public JAXBElement<BigInteger> createCycle(BigInteger value) {
        return new JAXBElement<BigInteger>(_Cycle_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargeCurrent")
    public JAXBElement<BigInteger> createChargeCurrent(BigInteger value) {
        return new JAXBElement<BigInteger>(_ChargeCurrent_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveSetting }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Channel1")
    public JAXBElement<ActiveSetting> createChannel1(ActiveSetting value) {
        return new JAXBElement<ActiveSetting>(_Channel1_QNAME, ActiveSetting.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActiveSetting }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Channel2")
    public JAXBElement<ActiveSetting> createChannel2(ActiveSetting value) {
        return new JAXBElement<ActiveSetting>(_Channel2_QNAME, ActiveSetting.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Capacity")
    public JAXBElement<BigInteger> createCapacity(BigInteger value) {
        return new JAXBElement<BigInteger>(_Capacity_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AccuTyp")
    public JAXBElement<BigInteger> createAccuTyp(BigInteger value) {
        return new JAXBElement<BigInteger>(_AccuTyp_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CellCount")
    public JAXBElement<BigInteger> createCellCount(BigInteger value) {
        return new JAXBElement<BigInteger>(_CellCount_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChargeStopMode")
    public JAXBElement<BigInteger> createChargeStopMode(BigInteger value) {
        return new JAXBElement<BigInteger>(_ChargeStopMode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Active_Setting")
    public JAXBElement<BigInteger> createActiveSetting(BigInteger value) {
        return new JAXBElement<BigInteger>(_ActiveSetting_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Active_Channel")
    public JAXBElement<BigInteger> createActiveChannel(BigInteger value) {
        return new JAXBElement<BigInteger>(_ActiveChannel_QNAME, BigInteger.class, null, value);
    }

}
