//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.5-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.29 at 04:00:35 pm CEST 
//


package gde.device.estner;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SettingType"/>
 *         &lt;element ref="{}Channel"/>
 *         &lt;element ref="{}AccuTyp"/>
 *         &lt;element ref="{}CurrentMode"/>
 *         &lt;element ref="{}Amount"/>
 *         &lt;element ref="{}Capacity"/>
 *         &lt;element ref="{}CellCount"/>
 *         &lt;element ref="{}Program"/>
 *         &lt;element ref="{}Cycle"/>
 *         &lt;element ref="{}ChargeMode"/>
 *         &lt;element ref="{}ChargeStopMode"/>
 *         &lt;element ref="{}ChargeCurrent"/>
 *         &lt;element ref="{}DisChargeCurrent"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "settingType",
    "channel",
    "accuTyp",
    "currentMode",
    "amount",
    "capacity",
    "cellCount",
    "program",
    "cycle",
    "chargeMode",
    "chargeStopMode",
    "chargeCurrent",
    "disChargeCurrent"
})
@XmlRootElement(name = "Setting")
public class Setting {

    @XmlElement(name = "SettingType", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String settingType;
    @XmlElement(name = "Channel", required = true)
    protected Integer channel;
    @XmlElement(name = "AccuTyp", required = true)
    protected Integer accuTyp;
    @XmlElement(name = "CurrentMode", required = true)
    protected Integer currentMode;
    @XmlElement(name = "Amount", required = true)
    protected Integer amount;
    @XmlElement(name = "Capacity", required = true)
    protected Integer capacity;
    @XmlElement(name = "CellCount", required = true)
    protected Integer cellCount;
    @XmlElement(name = "Program", required = true)
    protected Integer program;
    @XmlElement(name = "Cycle", required = true)
    protected Integer cycle;
    @XmlElement(name = "ChargeMode", required = true)
    protected Integer chargeMode;
    @XmlElement(name = "ChargeStopMode", required = true)
    protected Integer chargeStopMode;
    @XmlElement(name = "ChargeCurrent", required = true)
    protected Integer chargeCurrent;
    @XmlElement(name = "DisChargeCurrent", required = true)
    protected Integer disChargeCurrent;
    @XmlAttribute(name = "Name", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;

    /**
     * Gets the value of the settingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettingType() {
        return settingType;
    }

    /**
     * Sets the value of the settingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettingType(String value) {
        this.settingType = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setChannel(Integer value) {
        this.channel = value;
    }

    /**
     * Gets the value of the accuTyp property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAccuTyp() {
        return accuTyp;
    }

    /**
     * Sets the value of the accuTyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAccuTyp(Integer value) {
        this.accuTyp = value;
    }

    /**
     * Gets the value of the currentMode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCurrentMode() {
        return currentMode;
    }

    /**
     * Sets the value of the currentMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCurrentMode(Integer value) {
        this.currentMode = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAmount(Integer value) {
        this.amount = value;
    }

    /**
     * Gets the value of the capacity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCapacity() {
        return capacity;
    }

    /**
     * Sets the value of the capacity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCapacity(Integer value) {
        this.capacity = value;
    }

    /**
     * Gets the value of the cellCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCellCount() {
        return cellCount;
    }

    /**
     * Sets the value of the cellCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCellCount(Integer value) {
        this.cellCount = value;
    }

    /**
     * Gets the value of the program property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getProgram() {
        return program;
    }

    /**
     * Sets the value of the program property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setProgram(Integer value) {
        this.program = value;
    }

    /**
     * Gets the value of the cycle property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCycle() {
        return cycle;
    }

    /**
     * Sets the value of the cycle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCycle(Integer value) {
        this.cycle = value;
    }

    /**
     * Gets the value of the chargeMode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getChargeMode() {
        return chargeMode;
    }

    /**
     * Sets the value of the chargeMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setChargeMode(Integer value) {
        this.chargeMode = value;
    }

    /**
     * Gets the value of the chargeStopMode property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getChargeStopMode() {
        return chargeStopMode;
    }

    /**
     * Sets the value of the chargeStopMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setChargeStopMode(Integer value) {
        this.chargeStopMode = value;
    }

    /**
     * Gets the value of the chargeCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getChargeCurrent() {
        return chargeCurrent;
    }

    /**
     * Sets the value of the chargeCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setChargeCurrent(Integer value) {
        this.chargeCurrent = value;
    }

    /**
     * Gets the value of the disChargeCurrent property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDisChargeCurrent() {
        return disChargeCurrent;
    }

    /**
     * Sets the value of the disChargeCurrent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDisChargeCurrent(Integer value) {
        this.disChargeCurrent = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    public String toString() {
//    <Channel>1</Channel>
//    <AccuTyp>0</AccuTyp>
//    <CurrentMode>2</CurrentMode>
//    <Amount>0</Amount>
//    <Capacity>1000</Capacity>
//    <CellCount>34</CellCount>
//    <Program>2</Program>
//    <Cycle>0</Cycle>
//    <ChargeMode>0</ChargeMode>
//    <ChargeStopMode>0</ChargeStopMode>
//    <ChargeCurrent>100</ChargeCurrent>
//    <DisChargeCurrent>100</DisChargeCurrent>

    	return String.format("3 %d %02d %02d %02d %02d %02d %02d %05d %04d %04d %04d %02d 00 B", getChannel(), getAccuTyp(), getProgram(), getChargeMode(), getCurrentMode(), 
    			getChargeStopMode(), getCellCount(), getCapacity(), getChargeCurrent(), getDisChargeCurrent(), getAmount(), getCycle());
    }
}
